import React, { useState, useRef, useMemo, useEffect } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import { OrbitControls, Stars, Float, Sparkles, Cloud } from "@react-three/drei";
import * as THREE from 'three';
import axios from "axios";
import { motion, AnimatePresence } from "framer-motion";
import jsPDF from "jspdf";

const API_URL = "https://travel-planner-ai-qlbb.onrender.com/generate_plan"; 
const MAX_LIMIT = 2; 

const CITIES = {
  Delhi: { lat: 28.61, lon: 77.20 },
  Goa: { lat: 15.29, lon: 74.12 },
  Mumbai: { lat: 19.07, lon: 72.87 },
  Kolkata: { lat: 22.57, lon: 88.36 },
  Bangalore: { lat: 12.97, lon: 77.59 },
  Jaipur: { lat: 26.91, lon: 75.78 },
  Hyderabad: { lat: 17.38, lon: 78.48 },
  Varanasi: { lat: 25.31, lon: 82.97 }
};

// --- 3D EARTH (Desktop Only) - POLISHED ---
function HolographicEarth() {
  const meshRef = useRef();
  useFrame(() => { if (meshRef.current) meshRef.current.rotation.y += 0.001; });
  const points = useMemo(() => {
    const p = new Float32Array(3000 * 3);
    for (let i = 0; i < 3000; i++) {
        const theta = THREE.MathUtils.randFloatSpread(360); 
        const phi = THREE.MathUtils.randFloatSpread(360); 
        const x = 2.5 * Math.sin(theta) * Math.cos(phi);
        const y = 2.5 * Math.sin(theta) * Math.sin(phi);
        const z = 2.5 * Math.cos(theta);
        p[i*3] = x; p[i*3+1] = y; p[i*3+2] = z;
    }
    return p;
  }, []);
  return (
    <group>
        <points ref={meshRef}>
            <bufferGeometry><bufferAttribute attach="attributes-position" count={points.length/3} array={points} itemSize={3} /></bufferGeometry>
            {/* Increased opacity for brighter look */}
            <pointsMaterial size={0.02} color="#00e5ff" transparent opacity={0.8} sizeAttenuation />
        </points>
        <mesh><sphereGeometry args={[2.4, 32, 32]} /><meshBasicMaterial color="#000210" transparent opacity={0.95} /></mesh>
    </group>
  );
}

// --- MAIN APP ---
function App() {
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState(null);
  const [showResult, setShowResult] = useState(false);
  const [formData, setFormData] = useState({ source: "Delhi", destination: "Goa", days: 3, budget: "Luxury" });
  const [usageCount, setUsageCount] = useState(0);
  const [errorMsg, setErrorMsg] = useState("");
  const [isSpeaking, setIsSpeaking] = useState(false);
  
  // Mobile Check
  const [isMobile, setIsMobile] = useState(() => typeof window !== 'undefined' ? window.innerWidth < 768 : false);

  useEffect(() => {
    const handleResize = () => setIsMobile(window.innerWidth < 768);
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  const handleGenerate = async () => {
    if (usageCount >= MAX_LIMIT) return;
    setLoading(true);
    setErrorMsg("");
    try {
      const res = await axios.post(API_URL, formData);
      if (!res.data || typeof res.data !== 'object') {
          setErrorMsg("AI Response Error. Try Again.");
      } else {
          setPlan(res.data);
          setShowResult(true);
          setUsageCount(prev => prev + 1);
      }
    } catch (err) {
      console.error(err);
      setErrorMsg("Connection Error. Check Backend.");
    }
    setLoading(false);
  };

  const handleDownloadPDF = () => {
      if (!plan) return;
      try {
          const doc = new jsPDF();
          doc.setFont("helvetica", "bold"); doc.setFontSize(22); doc.setTextColor(0, 100, 255);
          doc.text(`TRIP TO ${formData.destination.toUpperCase()}`, 20, 20);
          doc.setFontSize(10); doc.setTextColor(100); doc.text("Generated by Agentic AI", 20, 28); doc.line(20, 32, 190, 32);
          const total = plan?.total_budget_estimated || "N/A";
          doc.setFontSize(12); doc.setTextColor(0); doc.text(`Total Budget: ${total} INR`, 20, 45);
          const flight = plan?.flight_selected?.airline || "Flight Info N/A";
          const fPrice = plan?.flight_selected?.price || "N/A";
          doc.text(`Flight: ${flight} (Cost: ${fPrice})`, 20, 55);
          const hotel = plan?.hotel_selected?.hotel_name || "Hotel Info N/A";
          doc.text(`Hotel: ${hotel}`, 20, 65);
          let y = 80; doc.setFontSize(14); doc.setTextColor(0, 100, 255); doc.text("Day-wise Itinerary:", 20, y); y += 10;
          const days = plan?.day_wise_plan || [];
          days.forEach((day, index) => {
              if (y > 270) { doc.addPage(); y = 20; }
              doc.setFont("helvetica", "bold"); doc.text(`Day ${day.day || index + 1}`, 20, y); y += 7;
              doc.setFont("helvetica", "normal");
              const content = day.activity || day.plan || "Relax and explore.";
              const splitText = doc.splitTextToSize(content, 170); doc.text(splitText, 20, y); y += (splitText.length * 6) + 10;
          });
          doc.save(`Trip_Plan_${formData.destination}.pdf`);
      } catch (e) {
          alert("PDF Error: " + e.message);
      }
  };

  const handleSpeak = () => {
      if (isSpeaking) { window.speechSynthesis.cancel(); setIsSpeaking(false); return; }
      if (!plan) return;
      window.speechSynthesis.cancel();
      const total = plan?.total_budget_estimated || "calculated";
      const text = `Namaste! Here is your plan for ${formData.destination}. Total budget is ${total} rupees. Enjoy!`;
      const utterance = new SpeechSynthesisUtterance(text);
      const voices = window.speechSynthesis.getVoices();
      const indianVoice = voices.find(v => v.lang.includes('IN') || v.name.includes('India'));
      if (indianVoice) utterance.voice = indianVoice;
      utterance.onend = () => setIsSpeaking(false);
      window.speechSynthesis.speak(utterance);
      setIsSpeaking(true);
  };

  const isLimitReached = usageCount >= MAX_LIMIT;

  return (
    <>
    <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Rajdhani:wght@500;600;700&display=swap');
        body { margin: 0; background: radial-gradient(circle at center, #0b1026 0%, #000000 100%); overflow: hidden; }
        .app-container { display: flex; width: 100vw; height: 100vh; font-family: 'Rajdhani', sans-serif; position: relative; }
        .sidebar { width: 380px; padding: 40px; background: rgba(5, 10, 20, 0.9); border-right: 1px solid #222; display: flex; flex-direction: column; justify-content: space-between; z-index: 60; position: relative; }
        .desktop-footer { position: absolute; bottom: 20px; left: 0; width: 100%; text-align: center; font-size: 0.75rem; color: #666; letter-spacing: 1px; border-top: 1px solid rgba(255,255,255,0.1); padding-top: 15px; }
        .canvas-container { flex: 1; position: relative; }
        .modal-overlay { position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.8); backdrop-filter: blur(8px); display: flex; justify-content: center; align-items: center; z-index: 100; }
        .modal-content { width: 550px; background: #080c14; border: 1px solid #00e5ff; border-radius: 12px; padding: 40px; box-shadow: 0 0 60px rgba(0, 229, 255, 0.15); position: relative; max-height: 85vh; overflow-y: auto; }
        
        @media (max-width: 768px) {
            .app-container { display: block; height: 100vh; overflow-y: auto; }
            .canvas-container { position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: 0; }
            .sidebar { width: 100%; height: 100%; min-height: 100vh; background: transparent; border: none; padding: 20px; box-sizing: border-box; position: relative; z-index: 10; display: flex; flex-direction: column; justify-content: center; align-items: center; }
            .glass-card { background: rgba(10, 15, 30, 0.85); backdrop-filter: blur(12px); padding: 25px; border-radius: 20px; border: 1px solid rgba(0, 229, 255, 0.2); box-shadow: 0 10px 40px rgba(0,0,0,0.6); width: 100%; max-width: 350px; }
            .modal-content { width: 90%; padding: 20px; margin-top: 20px; }
            .mobile-footer { margin-top: 20px; color: #888; font-size: 0.7rem; text-align: center; }
            .desktop-footer { display: none; }
        }
    `}</style>

    <div className="app-container">
      <div className="canvas-container">
         <Canvas camera={{ position: [0, 0, 7.5], fov: 45 }}>
            <color attach="background" args={[isMobile ? "#050a18" : "#000510"]} />
            <ambientLight intensity={0.5} />
            <pointLight position={[10, 10, 10]} intensity={2} color="#00e5ff" />
            {isMobile ? (
                /* More stars for mobile */
                <> <Stars radius={60} count={12000} factor={7} fade speed={2} /> <Sparkles count={500} scale={15} size={6} speed={0.5} color="#00e5ff" /> <Cloud opacity={0.2} speed={0.3} width={20} depth={2} segments={20} position={[0, 0, -10]} /> </>
            ) : (
                /* Denser stars for desktop */
                <> <Stars radius={100} count={6000} factor={5} fade /> <Sparkles count={100} scale={6} size={2} color="#00e5ff" /> <Float speed={2} rotationIntensity={0.2} floatIntensity={0.2}><HolographicEarth /></Float> </>
            )}
            <OrbitControls enableZoom={false} autoRotate autoRotateSpeed={isMobile ? 0.3 : 0.5} enablePan={false} />
        </Canvas>
      </div>

      <div className="sidebar">
        <div className={isMobile ? "glass-card" : ""}>
            <div style={{borderBottom: "1px solid rgba(255,255,255,0.1)", paddingBottom: "15px", marginBottom: "30px"}}>
                {/* NEW NEON LOGO STYLES APPLIED HERE */}
                <h1 style={logoStyle}>AGENTIC AI</h1>
                <h2 style={subLogoStyle}>TRAVEL PLANNING ASSISTANT</h2>
            </div>
            
            <div style={inputWrapper}><label style={labelStyle}>ORIGIN</label><select style={input} value={formData.source} onChange={e=>setFormData({...formData, source:e.target.value})}>{Object.keys(CITIES).map(c=><option key={c}>{c}</option>)}</select></div>
            <div style={inputWrapper}><label style={labelStyle}>DESTINATION</label><select style={input} value={formData.destination} onChange={e=>setFormData({...formData, destination:e.target.value})}>{Object.keys(CITIES).map(c=><option key={c}>{c}</option>)}</select></div>
            <div style={{display:"flex", gap:"10px"}}>
                <div style={inputWrapper}><label style={labelStyle}>DAYS</label><input type="number" style={input} value={formData.days} onChange={e=>setFormData({...formData, days:Number(e.target.value)})} /></div>
                <div style={inputWrapper}><label style={labelStyle}>TYPE</label><select style={input} value={formData.budget} onChange={e=>setFormData({...formData, budget:e.target.value})}><option>Budget</option><option>Luxury</option></select></div>
            </div>

            {errorMsg && <div style={{color: "#ff4444", fontSize: "0.8rem", marginTop: "10px"}}>⚠️ {errorMsg}</div>}

            <div style={{marginTop: "25px", display: "flex", justifyContent: "space-between", alignItems: "center"}}>
                <div style={{fontSize: "0.8rem", color: isLimitReached ? "#ff4444" : "#00ff88", border: `1px solid ${isLimitReached ? "#ff4444" : "#00ff88"}`, padding: "5px 10px", borderRadius: "4px", letterSpacing: "1px"}}>USES: {usageCount}/{MAX_LIMIT}</div>
                <motion.button whileHover={!isLimitReached ? { scale: 1.05 } : {}} onClick={handleGenerate} disabled={loading || isLimitReached} style={{...buttonStyle, background: isLimitReached ? "#333" : "#00e5ff", color: isLimitReached ? "#666" : "black", cursor: isLimitReached ? "not-allowed" : "pointer"}}>
                    {isLimitReached ? "LIMIT REACHED" : (loading ? "ANALYZING..." : "GENERATE PLAN")}
                </motion.button>
            </div>
            {isMobile && <div className="mobile-footer">DEC 2025 | Developed by Sayyed Mohsin Ali</div>}
        </div>
        {!isMobile && <div className="desktop-footer">DEC 2025 | Developed by Sayyed Mohsin Ali</div>}
      </div>

      <AnimatePresence>
        {showResult && plan && (
            <motion.div initial={{opacity: 0, scale: 0.9, y: 20}} animate={{opacity: 1, scale: 1, y: 0}} exit={{opacity: 0, scale: 0.9}} className="modal-overlay">
                <div className="modal-content">
                    <button onClick={() => {setShowResult(false); window.speechSynthesis.cancel(); setIsSpeaking(false);}} style={closeBtn}>×</button>
                    <h2 style={{color: "#00e5ff", textAlign: "center", marginBottom: "5px", textTransform: "uppercase", letterSpacing: "2px"}}>TRIP TO {formData.destination}</h2>
                    <p style={{textAlign: "center", color: "#888", fontSize: "1.2rem", marginBottom: "20px", fontWeight: "bold"}}>Total Budget: ₹{plan?.total_budget_estimated || "Calculating..."}</p>
                    <div style={{display: "flex", justifyContent: "center", gap: "15px", marginBottom: "20px"}}>
                        <button onClick={handleSpeak} style={{...actionBtn, background: isSpeaking ? "#ff4444" : "rgba(0, 229, 255, 0.1)"}}>{isSpeaking ? "🔇 Stop" : "🔊 Listen"}</button>
                        <button onClick={handleDownloadPDF} style={actionBtn}>📥 PDF</button>
                    </div>
                    <div style={gridContainer}>
                        <div style={card}><div style={label}>FLIGHT</div><div style={val}>{plan?.flight_selected?.airline || "Checking..."} (₹{plan?.flight_selected?.price || "N/A"})</div></div>
                        <div style={card}><div style={label}>HOTEL</div><div style={val}>{plan?.hotel_selected?.hotel_name || "Checking..."}</div></div>
                    </div>
                    <div style={{marginTop: "20px", padding: "15px", borderLeft: "3px solid #00e5ff", background: "rgba(0, 229, 255, 0.05)"}}>
                        <div style={label}>AI REASONING</div>
                        <div style={{fontSize: "0.9rem", color: "#ccc", fontStyle: "italic", marginTop: "5px"}}>"{plan?.reasoning || "Analyzing best options..."}"</div>
                    </div>
                    <h3 style={{color: "white", marginTop: "25px", borderBottom: "1px solid #333", paddingBottom: "10px", fontSize: "1.1rem"}}>ITINERARY</h3>
                    <div style={{maxHeight: "200px", overflowY: "auto", paddingRight: "10px"}}>
                        {(plan?.day_wise_plan || []).map((day, i) => (
                            <div key={i} style={{marginBottom: "20px"}}>
                                <strong style={{color: "#00e5ff", fontSize: "1rem"}}>DAY {day.day || (i+1)}</strong>
                                <p style={{margin: "5px 0 0 0", fontSize: "0.95rem", lineHeight: "1.6", color: "#ddd", textAlign: "justify"}}>{day.activity || day.plan || "Explore the city."}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </motion.div>
        )}
      </AnimatePresence>
    </div>
    </>
  );
}

// --- UPDATED STYLES WITH NEON GLOW ---
const logoStyle = { 
    fontSize: "2.5rem", margin: 0, color: "white", letterSpacing: "2px", lineHeight: "1",
    // NEON GLOW EFFECT
    textShadow: "0 0 5px #00e5ff, 0 0 10px #00e5ff, 0 0 20px #00e5ff"
};
const subLogoStyle = { 
    fontSize: "0.9rem", margin: "5px 0 0 0", color: "#00e5ff", letterSpacing: "1px", fontWeight: "500",
    // SUBTLE GLOW
    textShadow: "0 0 2px #00e5ff"
};

const inputWrapper = { marginBottom: "15px" };
const labelStyle = { fontSize: "0.8rem", color: "#00e5ff", fontWeight: "bold", marginBottom: "5px", letterSpacing: "1px", display: "block" };
const input = { width: "100%", padding: "12px", background: "#0b101a", border: "1px solid #333", color: "white", borderRadius: "4px", outline: "none", fontFamily: "inherit", fontSize: "1rem" };
const buttonStyle = { width: "100%", padding: "15px", border: "none", borderRadius: "4px", fontWeight: "bold", fontSize: "1rem", letterSpacing: "1px" };
const closeBtn = { position: "absolute", top: "15px", right: "20px", background: "none", border: "none", color: "#666", fontSize: "2rem", cursor: "pointer" };
const gridContainer = { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px", marginTop: "20px" };
const card = { background: "#111", padding: "15px", borderRadius: "6px", border: "1px solid #222" };
const label = { fontSize: "0.75rem", color: "#00e5ff", fontWeight: "bold", letterSpacing: "1px", textTransform: "uppercase" };
const val = { fontSize: "1rem", fontWeight: "bold", marginTop: "5px", wordBreak: "break-word" };
const actionBtn = { background: "rgba(0, 229, 255, 0.1)", border: "1px solid #00e5ff", color: "#00e5ff", padding: "8px 15px", borderRadius: "4px", cursor: "pointer", fontSize: "0.8rem", fontWeight: "bold", fontFamily: "inherit" };

export default App;
