import React, { useState, useRef, useMemo, useEffect } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import { OrbitControls, Stars, Float, Sparkles } from "@react-three/drei";
import * as THREE from 'three';
import axios from "axios";
import { motion, AnimatePresence } from "framer-motion";
import jsPDF from "jspdf"; // PDF Library

const API_URL = "https://travel-planner-ai-qlbb.onrender.com/generate_plan";
const MAX_LIMIT = 2; // Limit set to 2

const CITIES = {
  Delhi: { lat: 28.61, lon: 77.20 },
  Goa: { lat: 15.29, lon: 74.12 },
  Mumbai: { lat: 19.07, lon: 72.87 },
  Kolkata: { lat: 22.57, lon: 88.36 },
  Bangalore: { lat: 12.97, lon: 77.59 },
  Jaipur: { lat: 26.91, lon: 75.78 },
  Hyderabad: { lat: 17.38, lon: 78.48 },
  Varanasi: { lat: 25.31, lon: 82.97 }
};

// --- 3D EARTH ---
function HolographicEarth() {
  const meshRef = useRef();
  useFrame(() => { if (meshRef.current) meshRef.current.rotation.y += 0.001; });
  const points = useMemo(() => {
    const p = new Float32Array(3000 * 3);
    for (let i = 0; i < 3000; i++) {
        const theta = THREE.MathUtils.randFloatSpread(360); 
        const phi = THREE.MathUtils.randFloatSpread(360); 
        const x = 2.5 * Math.sin(theta) * Math.cos(phi);
        const y = 2.5 * Math.sin(theta) * Math.sin(phi);
        const z = 2.5 * Math.cos(theta);
        p[i*3] = x; p[i*3+1] = y; p[i*3+2] = z;
    }
    return p;
  }, []);
  return (
    <group>
        <points ref={meshRef}>
            <bufferGeometry><bufferAttribute attach="attributes-position" count={points.length/3} array={points} itemSize={3} /></bufferGeometry>
            <pointsMaterial size={0.02} color="#00e5ff" transparent opacity={0.6} sizeAttenuation />
        </points>
        <mesh><sphereGeometry args={[2.4, 32, 32]} /><meshBasicMaterial color="#000210" transparent opacity={0.95} /></mesh>
    </group>
  );
}

// --- MAIN APP ---
function App() {
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState(null);
  const [showResult, setShowResult] = useState(false);
  const [formData, setFormData] = useState({ source: "Delhi", destination: "Goa", days: 3, budget: "Luxury" });
  const [usageCount, setUsageCount] = useState(0);
  const [errorMsg, setErrorMsg] = useState("");
  const [isSpeaking, setIsSpeaking] = useState(false);

  // --- 1. GENERATE PLAN ---
  const handleGenerate = async () => {
    if (usageCount >= MAX_LIMIT) return;
    setLoading(true);
    setErrorMsg("");
    try {
      const res = await axios.post(API_URL, formData);
      if (!res.data || res.data.total_budget_estimated === 0) {
          setErrorMsg("AI Error. Please Try Again.");
      } else {
          setPlan(res.data);
          setShowResult(true);
          setUsageCount(prev => prev + 1);
      }
    } catch (err) {
      setErrorMsg("Connection Error: Check Backend.");
    }
    setLoading(false);
  };

  // --- 2. FIXED PDF DOWNLOAD ---
  const handleDownloadPDF = () => {
      if (!plan) return;
      try {
          const doc = new jsPDF();
          
          // Header
          doc.setFont("helvetica", "bold");
          doc.setFontSize(22);
          doc.setTextColor(0, 100, 255);
          doc.text(`TRIP TO ${formData.destination.toUpperCase()}`, 20, 20);
          
          doc.setFontSize(10);
          doc.setTextColor(100, 100, 100);
          doc.text("Generated by Agentic AI", 20, 28);
          doc.line(20, 32, 190, 32);

          // Summary
          doc.setFontSize(12);
          doc.setTextColor(0, 0, 0);
          doc.text(`Total Budget: ${plan.total_budget_estimated} INR`, 20, 45);
          
          // Flight & Hotel Info (Fixed Access)
          const flightName = plan.flight_selected?.airline || plan.flight_selected?.flight_id || "Flight";
          const flightPrice = plan.flight_selected?.price || "N/A";
          doc.text(`Flight: ${flightName} (Cost: ${flightPrice})`, 20, 55);

          const hotelName = plan.hotel_selected?.hotel_name || "Hotel";
          const hotelPrice = plan.hotel_selected?.price || "N/A";
          doc.text(`Hotel: ${hotelName} (Cost: ${hotelPrice})`, 20, 65);
          
          // Itinerary
          let y = 80;
          doc.setFontSize(14);
          doc.setTextColor(0, 100, 255);
          doc.text("Day-wise Itinerary:", 20, y);
          y += 10;

          plan.day_wise_plan.forEach((day) => {
              // Check page end
              if (y > 270) { doc.addPage(); y = 20; }
              
              doc.setFontSize(12);
              doc.setFont("helvetica", "bold");
              doc.setTextColor(0, 0, 0);
              doc.text(`Day ${day.day}`, 20, y);
              y += 7;
              
              doc.setFont("helvetica", "normal");
              doc.setFontSize(11);
              const splitText = doc.splitTextToSize(day.activity || day.plan, 170);
              doc.text(splitText, 20, y);
              y += (splitText.length * 6) + 10;
          });
          
          doc.save(`Trip_Plan_${formData.destination}.pdf`);
      } catch (e) {
          alert("Error downloading PDF: " + e.message);
      }
  };

  // --- 3. FIXED VOICE ASSISTANT ---
  const handleSpeak = () => {
      // If already speaking, stop it
      if (isSpeaking) {
          window.speechSynthesis.cancel();
          setIsSpeaking(false);
          return;
      }

      if (!plan) return;

      // Stop any previous speech
      window.speechSynthesis.cancel();

      const text = `Namaste! Here is your plan for ${formData.destination}. 
      I have found a flight with ${plan.flight_selected.airline || "preferred airline"} 
      and a stay at ${plan.hotel_selected.hotel_name || "a recommended hotel"}. 
      Your total estimated budget is ${plan.total_budget_estimated} rupees. 
      Enjoy your trip!`;

      const utterance = new SpeechSynthesisUtterance(text);
      
      // Try to find Indian voice, else use default
      const voices = window.speechSynthesis.getVoices();
      const indianVoice = voices.find(v => v.lang.includes('IN') || v.name.includes('India'));
      if (indianVoice) utterance.voice = indianVoice;
      
      utterance.rate = 1; 
      utterance.volume = 1;

      utterance.onend = () => setIsSpeaking(false);
      utterance.onerror = (e) => {
          console.error("Speech Error:", e);
          setIsSpeaking(false);
      };

      window.speechSynthesis.speak(utterance);
      setIsSpeaking(true);
  };

  // --- SAFE DATA HELPERS (Fixing "Itne Paise" Issue) ---
  const getFlightCost = () => {
      const price = plan?.flight_selected?.price;
      return price ? `₹${price}` : "₹5,000 (Est)";
  };

  const getHotelCost = () => {
      const price = plan?.hotel_selected?.price;
      return price ? `₹${price}` : "₹3,000 (Est)";
  };

  const isLimitReached = usageCount >= MAX_LIMIT;

  return (
    <>
    <style>{`@import url('https://fonts.googleapis.com/css2?family=Rajdhani:wght@500;600;700&display=swap');`}</style>
    <div style={containerStyle}>
      <div style={crtOverlayStyle}></div>
      <div style={vignetteStyle}></div>

      {/* SIDEBAR */}
      <div style={sidebarStyle}>
        <div style={{borderBottom: "1px solid #333", paddingBottom: "20px", marginBottom: "30px"}}>
            <h1 style={logoStyle}>AGENTIC AI</h1>
            <h2 style={subLogoStyle}>TRAVEL PLANNING ASSISTANT</h2>
        </div>
        
        <div style={inputWrapper}><label style={labelStyle}>ORIGIN</label><select style={input} value={formData.source} onChange={e=>setFormData({...formData, source:e.target.value})}>{Object.keys(CITIES).map(c=><option key={c}>{c}</option>)}</select></div>
        <div style={inputWrapper}><label style={labelStyle}>DESTINATION</label><select style={input} value={formData.destination} onChange={e=>setFormData({...formData, destination:e.target.value})}>{Object.keys(CITIES).map(c=><option key={c}>{c}</option>)}</select></div>
        <div style={{display:"flex", gap:"10px"}}>
            <div style={inputWrapper}><label style={labelStyle}>DAYS</label><input type="number" style={input} value={formData.days} onChange={e=>setFormData({...formData, days:Number(e.target.value)})} /></div>
            <div style={inputWrapper}><label style={labelStyle}>TYPE</label><select style={input} value={formData.budget} onChange={e=>setFormData({...formData, budget:e.target.value})}><option>Budget</option><option>Luxury</option></select></div>
        </div>

        {errorMsg && <div style={{color: "#ff4444", fontSize: "0.8rem", marginTop: "10px"}}>⚠️ {errorMsg}</div>}

        <div style={{marginTop: "30px", display: "flex", justifyContent: "space-between", alignItems: "center"}}>
             <div style={{fontSize: "0.8rem", color: isLimitReached ? "#ff4444" : "#00ff88", border: `1px solid ${isLimitReached ? "#ff4444" : "#00ff88"}`, padding: "5px 10px", borderRadius: "4px", letterSpacing: "1px"}}>USES: {usageCount}/{MAX_LIMIT}</div>
             <motion.button whileHover={!isLimitReached ? { scale: 1.05 } : {}} onClick={handleGenerate} disabled={loading || isLimitReached} style={{...buttonStyle, background: isLimitReached ? "#333" : "#00e5ff", color: isLimitReached ? "#666" : "black", cursor: isLimitReached ? "not-allowed" : "pointer"}}>
                {isLimitReached ? "LIMIT REACHED" : (loading ? "ANALYZING..." : "GENERATE PLAN")}
            </motion.button>
        </div>
      </div>

      {/* RESULT MODAL */}
      <AnimatePresence>
        {showResult && plan && (
            <motion.div initial={{opacity: 0, scale: 0.9, y: 20}} animate={{opacity: 1, scale: 1, y: 0}} exit={{opacity: 0, scale: 0.9}} style={modalOverlay}>
                <div style={modalContent}>
                    <button onClick={() => {setShowResult(false); window.speechSynthesis.cancel(); setIsSpeaking(false);}} style={closeBtn}>×</button>
                    
                    <h2 style={{color: "#00e5ff", textAlign: "center", marginBottom: "5px", textTransform: "uppercase", letterSpacing: "2px"}}>TRIP TO {formData.destination}</h2>
                    <p style={{textAlign: "center", color: "#888", fontSize: "1.2rem", marginBottom: "20px", fontWeight: "bold"}}>Total Budget: ₹{plan.total_budget_estimated}</p>

                    {/* ACTION BUTTONS (Voice & PDF) */}
                    <div style={{display: "flex", justifyContent: "center", gap: "15px", marginBottom: "20px"}}>
                        <button onClick={handleSpeak} style={{...actionBtn, background: isSpeaking ? "#ff4444" : "rgba(0, 229, 255, 0.1)"}}>
                            {isSpeaking ? "🔇 Stop Voice" : "🔊 Listen Plan"}
                        </button>
                        <button onClick={handleDownloadPDF} style={actionBtn}>
                            📥 Download PDF
                        </button>
                    </div>

                    <div style={gridContainer}>
                        <div style={card}>
                            <div style={label}>FLIGHT INFO</div>
                            <div style={val}>{plan.flight_selected?.airline || "Flight"}</div>
                            <div style={subVal}>{getFlightCost()}</div>
                        </div>
                        <div style={card}>
                            <div style={label}>HOTEL INFO</div>
                            <div style={val}>{plan.hotel_selected?.hotel_name || "Hotel"}</div>
                            <div style={subVal}>{getHotelCost()}</div>
                        </div>
                    </div>

                    <div style={{marginTop: "20px", padding: "15px", borderLeft: "3px solid #00e5ff", background: "rgba(0, 229, 255, 0.05)"}}>
                        <div style={label}>AI REASONING</div>
                        <div style={{fontSize: "0.9rem", color: "#ccc", fontStyle: "italic", marginTop: "5px"}}>"{plan.reasoning}"</div>
                    </div>

                    <h3 style={{color: "white", marginTop: "25px", borderBottom: "1px solid #333", paddingBottom: "10px", fontSize: "1.1rem"}}>ITINERARY</h3>
                    <div style={{maxHeight: "200px", overflowY: "auto", paddingRight: "10px"}}>
                        {plan.day_wise_plan.map((day, i) => (
                            <div key={i} style={{marginBottom: "20px"}}>
                                <strong style={{color: "#00e5ff", fontSize: "1rem"}}>DAY {day.day}</strong>
                                <p style={{margin: "5px 0 0 0", fontSize: "0.95rem", lineHeight: "1.6", color: "#ddd", textAlign: "justify"}}>{day.activity || day.plan}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </motion.div>
        )}
      </AnimatePresence>

      {/* 3D VISUALIZER */}
      <div style={{flex: 1, position: "relative"}}>
         <Canvas camera={{ position: [0, 0, 7.5], fov: 45 }}>
            <color attach="background" args={["#000510"]} />
            <ambientLight intensity={0.5} />
            <pointLight position={[10, 10, 10]} intensity={2} color="#00e5ff" />
            <Stars radius={100} count={5000} factor={4} fade />
            <Sparkles count={100} scale={6} size={2} color="#00e5ff" />
            <Float speed={2} rotationIntensity={0.2} floatIntensity={0.2}><HolographicEarth /></Float>
            <OrbitControls enableZoom={false} autoRotate autoRotateSpeed={0.5} />
        </Canvas>
      </div>
    </div>
    </>
  );
}

// --- STYLES ---
const containerStyle = { display: "flex", width: "100vw", height: "100vh", background: "#000510", color: "white", fontFamily: "'Rajdhani', sans-serif", overflow: "hidden", position: "relative" };
const vignetteStyle = { position: "absolute", top: 0, left: 0, width: "100%", height: "100%", zIndex: 50, pointerEvents: "none", background: "radial-gradient(circle, rgba(0,0,0,0) 60%, rgba(0,0,0,0.8) 100%)", boxShadow: "inset 0 0 50px rgba(0,0,0,0.9)" };
const crtOverlayStyle = { position: "absolute", top: 0, left: 0, width: "100%", height: "100%", zIndex: 40, pointerEvents: "none", background: "linear-gradient(rgba(18, 16, 16, 0) 50%, rgba(0, 0, 0, 0.1) 50%)", backgroundSize: "100% 4px" };
const sidebarStyle = { width: "380px", padding: "40px", background: "rgba(5, 10, 20, 0.9)", borderRight: "1px solid #222", display: "flex", flexDirection: "column", zIndex: 60, position: "relative" };
const logoStyle = { fontSize: "2.5rem", margin: 0, color: "white", letterSpacing: "2px", lineHeight: "1" };
const subLogoStyle = { fontSize: "0.9rem", margin: 0, color: "#00e5ff", letterSpacing: "1px", fontWeight: "500" };
const inputWrapper = { marginBottom: "20px" };
const labelStyle = { fontSize: "0.8rem", color: "#00e5ff", fontWeight: "bold", marginBottom: "8px", letterSpacing: "1px", display: "block" };
const input = { width: "100%", padding: "12px", background: "#0b101a", border: "1px solid #333", color: "white", borderRadius: "4px", outline: "none", fontFamily: "inherit", fontSize: "1rem" };
const buttonStyle = { padding: "15px", border: "none", borderRadius: "4px", fontWeight: "bold", fontSize: "1rem", letterSpacing: "1px" };
const modalOverlay = { position: "absolute", top: 0, left: 0, width: "100%", height: "100%", background: "rgba(0,0,0,0.8)", backdropFilter: "blur(8px)", display: "flex", justifyContent: "center", alignItems: "center", zIndex: 100 };
const modalContent = { width: "550px", background: "#080c14", border: "1px solid #00e5ff", borderRadius: "12px", padding: "40px", boxShadow: "0 0 60px rgba(0, 229, 255, 0.15)", position: "relative" };
const closeBtn = { position: "absolute", top: "15px", right: "20px", background: "none", border: "none", color: "#666", fontSize: "2rem", cursor: "pointer" };
const gridContainer = { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "20px", marginTop: "20px" };
const card = { background: "#111", padding: "15px", borderRadius: "6px", border: "1px solid #222" };
const label = { fontSize: "0.75rem", color: "#00e5ff", fontWeight: "bold", letterSpacing: "1px", textTransform: "uppercase" };
const val = { fontSize: "1.1rem", fontWeight: "bold", marginTop: "5px" };
const subVal = { fontSize: "0.9rem", color: "#00ff88", marginTop: "2px" };
const actionBtn = { background: "rgba(0, 229, 255, 0.1)", border: "1px solid #00e5ff", color: "#00e5ff", padding: "10px 20px", borderRadius: "4px", cursor: "pointer", fontSize: "0.8rem", fontWeight: "bold", fontFamily: "inherit" };

export default App;
